# Generated by Django 4.0 on 2022-03-04 14:33

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=system.models.uploaded_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('bike_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('cost_par_day', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
