# Generated by Django 4.0 on 2022-03-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_order_privatemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
    ]
